*&---------------------------------------------------------------------*
*& Report ZDPM_TABLS
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDPM_TABLS.
*PARAMETERS : P_KUNNR TYPE KNA1-KUNNR , P_LAND1 TYPE KNA1-LAND1 .
*TYPES : BEGIN OF TY_KNA1 ,
*         KUNNR TYPE KNA1-KUNNR ,
*         LAND1 TYPE KNA1-LAND1 ,
*         NAME1 TYPE KNA1-NAME1 ,
*         ORTO1 TYPE KNA1-ORT01 ,
*       END OF TY_KNA1.
*
*DATA : IT_TAB TYPE  STANDARD TABLE OF TY_KNA1 , WA_TAB TYPE TY_KNA1.
*SELECT KUNNR LAND1 NAME1 ORT01 INTO WA_TAB FROM KNA1 WHERE KUNNR = P_KUNNR OR LAND1 = P_LAND1.
*  APPEND WA_TAB TO IT_TAB.
*  ENDSELECT.
* LOOP AT IT_TAB INTO WA_TAB.
*   WRITE: / WA_TAB-KUNNR , WA_TAB-LAND1 , WA_TAB-NAME1 , WA_TAB-ORTO1.
*  ENDLOOP.


*  SELECT KUNNR LAND1 NAME1 ORTO1 INTO TABLE IT_TAB
DATA LV_KUNNR TYPE KNA1-KUNNR.

SELECT-OPTIONS S_KUNNR FOR LV_KUNNR.
TYPES : BEGIN OF TY_KNA1 , KUNNR TYPE KNA1-KUNNR , LAND1 TYPE KNA1-LAND1 , NAME1 TYPE KNA1-NAME1, ORT01 TYPE KNA1-ORT01,
  END OF TY_KNA1.
DATA : IT_TAB TYPE TABLE OF TY_KNA1 , WA_KNA1 TYPE TY_KNA1.

SELECT KUNNR LAND1 NAME1 ORT01 INTO WA_KNA1 FROM KNA1 WHERE KUNNR IN S_KUNNR.
  APPEND WA_KNA1 TO IT_TAB.
 ENDSELECT.
 LOOP AT IT_TAB INTO WA_KNA1.
   WRITE : / WA_KNA1-KUNNR , WA_KNA1-LAND1 , WA_KNA1-NAME1 , WA_KNA1-ORT01.
 ENDLOOP.

*SELECT KUNNR LAND1 NAME1 ORT01 INTO TABLE IT_TAB FROM KNA1 WHERE KUNNR IN S_KUNNR.
*LOOP AT IT_TAB INTO WA_KNA1.
*  WRITE : / WA_KNA1-KUNNR , WA_KNA1-LAND1 , WA_KNA1-NAME1 , WA_KNA1-ORT01.
* ENDLOOP.